set(SRC_DIR "${ClickHouse_SOURCE_DIR}/contrib/openzl")

set(OPENZL_SOURCES
    ${SRC_DIR}/src/openzl/codecs/bitpack/common_bitpack_kernel.c
    ${SRC_DIR}/src/openzl/codecs/bitpack/decode_bitpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/bitpack/encode_bitpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/bitunpack/decode_bitunpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/bitunpack/encode_bitunpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/common/fast_table.c
    ${SRC_DIR}/src/openzl/codecs/common/window.c
    ${SRC_DIR}/src/openzl/codecs/concat/decode_concat_binding.c
    ${SRC_DIR}/src/openzl/codecs/concat/encode_concat_binding.c
    ${SRC_DIR}/src/openzl/codecs/constant/decode_constant_binding.c
    ${SRC_DIR}/src/openzl/codecs/constant/decode_constant_kernel.c
    ${SRC_DIR}/src/openzl/codecs/constant/encode_constant_binding.c
    ${SRC_DIR}/src/openzl/codecs/constant/encode_constant_kernel.c
    ${SRC_DIR}/src/openzl/codecs/conversion/decode_conversion_binding.c
    ${SRC_DIR}/src/openzl/codecs/conversion/encode_conversion_binding.c
    ${SRC_DIR}/src/openzl/codecs/conversion/encode_setStringSizes_binding.c
    ${SRC_DIR}/src/openzl/codecs/conversion/graph_conversion.c
    ${SRC_DIR}/src/openzl/codecs/decoder_registry.c
    ${SRC_DIR}/src/openzl/codecs/dedup/decode_dedup_binding.c
    ${SRC_DIR}/src/openzl/codecs/dedup/encode_dedup_binding.c
    ${SRC_DIR}/src/openzl/codecs/delta/decode_delta_binding.c
    ${SRC_DIR}/src/openzl/codecs/delta/decode_delta_kernel.c
    ${SRC_DIR}/src/openzl/codecs/delta/encode_delta_binding.c
    ${SRC_DIR}/src/openzl/codecs/delta/encode_delta_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatchN_byTag/decode_dispatchN_byTag_binding.c
    ${SRC_DIR}/src/openzl/codecs/dispatchN_byTag/decode_dispatchN_byTag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatchN_byTag/encode_dispatchN_byTag_binding.c
    ${SRC_DIR}/src/openzl/codecs/dispatchN_byTag/encode_dispatchN_byTag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_by_tag/decode_dispatch_by_tag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_by_tag/encode_dispatch_by_tag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_string/decode_dispatch_string_binding.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_string/decode_dispatch_string_kernel.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_string/encode_dispatch_string_binding.c
    ${SRC_DIR}/src/openzl/codecs/dispatch_string/encode_dispatch_string_kernel.c
    ${SRC_DIR}/src/openzl/codecs/divide_by/decode_divide_by_binding.c
    ${SRC_DIR}/src/openzl/codecs/divide_by/decode_divide_by_kernel.c
    ${SRC_DIR}/src/openzl/codecs/divide_by/encode_divide_by_binding.c
    ${SRC_DIR}/src/openzl/codecs/divide_by/encode_divide_by_kernel.c
    ${SRC_DIR}/src/openzl/codecs/encoder_registry.c
    ${SRC_DIR}/src/openzl/codecs/entropy/decode_entropy_binding.c
    ${SRC_DIR}/src/openzl/codecs/entropy/decode_huffman_kernel.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/decode_entropy_decompress.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/decode_fse_kernel.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/decode_huf_avx2_decompress.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/encode_entropy_compress.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/encode_fse_kernel.c
    ${SRC_DIR}/src/openzl/codecs/entropy/deprecated/encode_huf_avx2_compress.c
    ${SRC_DIR}/src/openzl/codecs/entropy/encode_entropy_binding.c
    ${SRC_DIR}/src/openzl/codecs/entropy/encode_entropy_selector.c
    ${SRC_DIR}/src/openzl/codecs/entropy/encode_huffman_kernel.c
    ${SRC_DIR}/src/openzl/codecs/flatpack/decode_flatpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/flatpack/decode_flatpack_kernel.c
    ${SRC_DIR}/src/openzl/codecs/flatpack/encode_flatpack_binding.c
    ${SRC_DIR}/src/openzl/codecs/flatpack/encode_flatpack_kernel.c
    ${SRC_DIR}/src/openzl/codecs/float_deconstruct/decode_float_deconstruct_binding.c
    ${SRC_DIR}/src/openzl/codecs/float_deconstruct/decode_float_deconstruct_kernel.c
    ${SRC_DIR}/src/openzl/codecs/float_deconstruct/encode_float_deconstruct_binding.c
    ${SRC_DIR}/src/openzl/codecs/float_deconstruct/encode_float_deconstruct_kernel.c
    ${SRC_DIR}/src/openzl/codecs/interleave/decode_interleave_binding.c
    ${SRC_DIR}/src/openzl/codecs/interleave/encode_interleave_binding.c
    ${SRC_DIR}/src/openzl/codecs/lz/decode_field_lz.c
    ${SRC_DIR}/src/openzl/codecs/lz/decode_lz_binding.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_field_lz.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_field_lz_literals_selector.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_field_lz_sequences.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_lz_binding.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_match_finder_fast_field_lz.c
    ${SRC_DIR}/src/openzl/codecs/lz/encode_match_finder_greedy_field_lz.c
    ${SRC_DIR}/src/openzl/codecs/merge_sorted/decode_merge_sorted_binding.c
    ${SRC_DIR}/src/openzl/codecs/merge_sorted/decode_merge_sorted_kernel.c
    ${SRC_DIR}/src/openzl/codecs/merge_sorted/encode_merge_sorted_binding.c
    ${SRC_DIR}/src/openzl/codecs/merge_sorted/encode_merge_sorted_kernel.c
    ${SRC_DIR}/src/openzl/codecs/parse_int/decode_parse_int_binding.c
    ${SRC_DIR}/src/openzl/codecs/parse_int/decode_parse_int_kernel.c
    ${SRC_DIR}/src/openzl/codecs/parse_int/encode_parse_int_binding.c
    ${SRC_DIR}/src/openzl/codecs/parse_int/encode_parse_int_kernel.c
    ${SRC_DIR}/src/openzl/codecs/prefix/decode_prefix_binding.c
    ${SRC_DIR}/src/openzl/codecs/prefix/decode_prefix_kernel.c
    ${SRC_DIR}/src/openzl/codecs/prefix/encode_prefix_binding.c
    ${SRC_DIR}/src/openzl/codecs/prefix/encode_prefix_kernel.c
    ${SRC_DIR}/src/openzl/codecs/quantize/common_quantize.c
    ${SRC_DIR}/src/openzl/codecs/quantize/decode_quantize_binding.c
    ${SRC_DIR}/src/openzl/codecs/quantize/decode_quantize_kernel.c
    ${SRC_DIR}/src/openzl/codecs/quantize/encode_quantize_binding.c
    ${SRC_DIR}/src/openzl/codecs/quantize/encode_quantize_kernel.c
    ${SRC_DIR}/src/openzl/codecs/range_pack/decode_range_pack_binding.c
    ${SRC_DIR}/src/openzl/codecs/range_pack/decode_range_pack_kernel.c
    ${SRC_DIR}/src/openzl/codecs/range_pack/encode_range_pack_binding.c
    ${SRC_DIR}/src/openzl/codecs/range_pack/encode_range_pack_kernel.c
    ${SRC_DIR}/src/openzl/codecs/rolz/decode_experimental_dec.c
    ${SRC_DIR}/src/openzl/codecs/rolz/decode_fast_dec.c
    ${SRC_DIR}/src/openzl/codecs/rolz/decode_rolz_binding.c
    ${SRC_DIR}/src/openzl/codecs/rolz/decode_rolz_kernel.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_experimental_enc.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_fast_enc.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_match_finder_double_fast_lc.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_match_finder_lazy.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_rolz_binding.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_rolz_kernel.c
    ${SRC_DIR}/src/openzl/codecs/rolz/encode_rolz_sequences.c
    ${SRC_DIR}/src/openzl/codecs/splitByStruct/decode_splitByStruct_binding.c
    ${SRC_DIR}/src/openzl/codecs/splitByStruct/decode_splitByStruct_kernel.c
    ${SRC_DIR}/src/openzl/codecs/splitByStruct/encode_splitByStruct_binding.c
    ${SRC_DIR}/src/openzl/codecs/splitByStruct/encode_splitByStruct_kernel.c
    ${SRC_DIR}/src/openzl/codecs/splitN/decode_splitN_binding.c
    ${SRC_DIR}/src/openzl/codecs/splitN/decode_splitN_kernel.c
    ${SRC_DIR}/src/openzl/codecs/splitN/encode_splitN_binding.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/decode_tokenize2to1_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/decode_tokenize4to2_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/decode_tokenizeVarto4_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/decode_tokenize_binding.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/decode_tokenize_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenize2to1_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenize4to2_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenizeVarto4_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenize_binding.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenize_kernel.c
    ${SRC_DIR}/src/openzl/codecs/tokenize/encode_tokenize_kernel_sort.c
    ${SRC_DIR}/src/openzl/codecs/transpose/decode_transpose_binding.c
    ${SRC_DIR}/src/openzl/codecs/transpose/decode_transpose_kernel.c
    ${SRC_DIR}/src/openzl/codecs/transpose/encode_transpose_binding.c
    ${SRC_DIR}/src/openzl/codecs/transpose/encode_transpose_kernel.c
    ${SRC_DIR}/src/openzl/codecs/zigzag/decode_zigzag_binding.c
    ${SRC_DIR}/src/openzl/codecs/zigzag/decode_zigzag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/zigzag/encode_zigzag_binding.c
    ${SRC_DIR}/src/openzl/codecs/zigzag/encode_zigzag_kernel.c
    ${SRC_DIR}/src/openzl/codecs/zstd/decode_zstd_binding.c
    ${SRC_DIR}/src/openzl/codecs/zstd/encode_zstd_binding.c
    ${SRC_DIR}/src/openzl/common/a1cbor_helpers.c
    ${SRC_DIR}/src/openzl/common/allocation.c
    ${SRC_DIR}/src/openzl/common/errors.c
    ${SRC_DIR}/src/openzl/common/limits.c
    ${SRC_DIR}/src/openzl/common/logging.c
    ${SRC_DIR}/src/openzl/common/opaque.c
    ${SRC_DIR}/src/openzl/common/operation_context.c
    ${SRC_DIR}/src/openzl/common/refcount.c
    ${SRC_DIR}/src/openzl/common/stream.c
    ${SRC_DIR}/src/openzl/common/wire_format.c
    ${SRC_DIR}/src/openzl/compress/cctx.c
    ${SRC_DIR}/src/openzl/compress/cgraph.c
    ${SRC_DIR}/src/openzl/compress/cgraph_validation.c
    ${SRC_DIR}/src/openzl/compress/cnode.c
    ${SRC_DIR}/src/openzl/compress/cnodes.c
    ${SRC_DIR}/src/openzl/compress/compress2.c
    ${SRC_DIR}/src/openzl/compress/compressor_serialization.c
    ${SRC_DIR}/src/openzl/compress/dyngraph_interface.c
    ${SRC_DIR}/src/openzl/compress/enc_interface.c
    ${SRC_DIR}/src/openzl/compress/encode_frameheader.c
    ${SRC_DIR}/src/openzl/compress/gcparams.c
    ${SRC_DIR}/src/openzl/compress/graph_registry.c
    ${SRC_DIR}/src/openzl/compress/graphmgr.c
    ${SRC_DIR}/src/openzl/compress/graphs/automated_compressor_explorer.c
    ${SRC_DIR}/src/openzl/compress/graphs/generic_clustering_graph.c
    ${SRC_DIR}/src/openzl/compress/graphs/simple_data_description_language.c
    ${SRC_DIR}/src/openzl/compress/graphs/simple_data_description_language_source_code.c
    ${SRC_DIR}/src/openzl/compress/graphs/split_graph.c
    ${SRC_DIR}/src/openzl/compress/implicit_conversion.c
    ${SRC_DIR}/src/openzl/compress/localparams.c
    ${SRC_DIR}/src/openzl/compress/name.c
    ${SRC_DIR}/src/openzl/compress/nodemgr.c
    ${SRC_DIR}/src/openzl/compress/rtgraphs.c
    ${SRC_DIR}/src/openzl/compress/segmenter.c
    ${SRC_DIR}/src/openzl/compress/selector.c
    ${SRC_DIR}/src/openzl/compress/selectors/ml/features.c
    ${SRC_DIR}/src/openzl/compress/selectors/ml/gbt.c
    ${SRC_DIR}/src/openzl/compress/selectors/ml/mlselector.c
    ${SRC_DIR}/src/openzl/compress/selectors/ml/selector_numeric_model.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_brute_force.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_compress.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_constant.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_genericLZ.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_numeric.c
    ${SRC_DIR}/src/openzl/compress/selectors/selector_store.c
    ${SRC_DIR}/src/openzl/compress/trStates.c
    ${SRC_DIR}/src/openzl/decompress/decode_frameheader.c
    ${SRC_DIR}/src/openzl/decompress/decompress2.c
    ${SRC_DIR}/src/openzl/decompress/dictx.c
    ${SRC_DIR}/src/openzl/decompress/dtransforms.c
    ${SRC_DIR}/src/openzl/decompress/gdparams.c
    ${SRC_DIR}/src/openzl/decompress/reflection.c
    ${SRC_DIR}/src/openzl/fse/common/debug.c
    ${SRC_DIR}/src/openzl/fse/common/entropy_common.c
    ${SRC_DIR}/src/openzl/fse/common/error_private.c
    ${SRC_DIR}/src/openzl/fse/compress/fse_compress.c
    ${SRC_DIR}/src/openzl/fse/compress/hist.c
    ${SRC_DIR}/src/openzl/fse/compress/huf_compress.c
    ${SRC_DIR}/src/openzl/fse/decompress/fse_decompress.c
    ${SRC_DIR}/src/openzl/fse/decompress/huf_decompress.c
    ${SRC_DIR}/src/openzl/shared/a1cbor.c
    ${SRC_DIR}/src/openzl/shared/clustering_common.c
    ${SRC_DIR}/src/openzl/shared/clustering_compress.c
    ${SRC_DIR}/src/openzl/shared/data_stats.c
    ${SRC_DIR}/src/openzl/shared/detail/pdqsort1.c
    ${SRC_DIR}/src/openzl/shared/detail/pdqsort2.c
    ${SRC_DIR}/src/openzl/shared/detail/pdqsort4.c
    ${SRC_DIR}/src/openzl/shared/detail/pdqsort8.c
    ${SRC_DIR}/src/openzl/shared/estimate.c
    ${SRC_DIR}/src/openzl/shared/histogram.c
    ${SRC_DIR}/src/openzl/shared/numeric_operations.c
)

add_library(_openzl ${OPENZL_SOURCES})
target_include_directories(_openzl SYSTEM PUBLIC "${SRC_DIR}/include")
target_include_directories(_openzl SYSTEM PRIVATE "${SRC_DIR}/src")
target_link_libraries(_openzl PUBLIC ch_contrib::zstd)
add_library(ch_contrib::openzl ALIAS _openzl)